# Generated by Django 6.0.6 on 2026-07-21 03:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('volunteers', '0004_role_documentation_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='shift',
            name='external_uid',
            field=models.CharField(blank=True, help_text='UID from external source (e.g. ICS feed) for idempotent syncing.', max_length=255, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='shift',
            name='talk_url',
            field=models.URLField(blank=True, help_text='Link to the talk on the conference website.'),
        ),
    ]
