# Generated by Django 6.0.6 on 2026-08-12 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('volunteers', '0010_volunteer_chair_group'),
    ]

    operations = [
        migrations.AddField(
            model_name='volunteersignup',
            name='welcomed',
            field=models.BooleanField(default=False, help_text="The welcome email was sent off the back of this signup — the volunteer's first."),
        ),
    ]
