# Generated by Django 6.0.6 on 2026-08-12 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('volunteers', '0011_volunteersignup_welcomed'),
    ]

    operations = [
        migrations.AddField(
            model_name='volunteersignup',
            name='digested',
            field=models.BooleanField(default=False, help_text="This signup has appeared in a 'your shifts today' digest."),
        ),
    ]
