# Generated by Django 6.0.6 on 2026-09-04 01:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('volunteers', '0012_volunteersignup_digested'),
    ]

    operations = [
        migrations.AddField(
            model_name='role',
            name='reporting_location',
            field=models.CharField(blank=True, help_text='Where volunteers in this role go to start a shift — e.g. the registration desk. Individual shifts can override this.', max_length=200),
        ),
        migrations.AddField(
            model_name='shift',
            name='reporting_location',
            field=models.CharField(blank=True, help_text="Where to go to start this shift. Leave blank to use the role's reporting location.", max_length=200),
        ),
    ]
