# Generated by Django 4.1.6 on 2023-05-07 02:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Brand",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("brand_id", models.CharField(max_length=32)),
                ("name", models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="List",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("list_id", models.CharField(max_length=32)),
                ("name", models.CharField(max_length=100)),
                ("active", models.BooleanField(default=True)),
                ("default", models.BooleanField(default=False)),
                (
                    "brand",
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="sendy.brand"),
                ),
            ],
        ),
    ]
