# Generated by Django 4.2.11 on 2025-08-31 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TravelRegistration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=20)),
                ('preferred_contact', models.CharField(choices=[('whatsapp', 'WhatsApp'), ('signal', 'Signal'), ('sms', 'SMS')], default='whatsapp', max_length=20)),
                ('arrival_airline', models.CharField(max_length=100)),
                ('arrival_flight_number', models.CharField(max_length=20)),
                ('arrival_time', models.DateTimeField()),
                ('arrival_airport', models.CharField(max_length=100)),
                ('departure_airline', models.CharField(blank=True, max_length=100, null=True)),
                ('departure_flight_number', models.CharField(blank=True, max_length=20, null=True)),
                ('departure_time', models.DateTimeField(blank=True, null=True)),
                ('departure_airport', models.CharField(blank=True, max_length=100, null=True)),
                ('departure_destination', models.CharField(blank=True, max_length=100, null=True)),
                ('emergency_contact_name', models.CharField(max_length=200)),
                ('emergency_contact_phone', models.CharField(max_length=20)),
                ('emergency_contact_relationship', models.CharField(blank=True, max_length=100, null=True)),
                ('status', models.CharField(choices=[('pending_arrival', 'Pending Arrival'), ('arrived_safely', 'Arrived Safely'), ('pending_departure', 'Pending Departure'), ('all_checks_complete', 'All Checks Complete'), ('check_failed', 'Check Failed'), ('emergency_contact_notified', 'Emergency Contact Notified'), ('cancelled', 'Cancelled')], default='pending_arrival', max_length=30)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Travel Registration',
                'verbose_name_plural': 'Travel Registrations',
                'ordering': ['arrival_time'],
            },
        ),
    ]
