# Generated by Django 4.2.11 on 2025-09-04 01:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel_safety', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='travelregistration',
            name='accommodation',
            field=models.TextField(blank=True, help_text='Where you are staying in Chicago', null=True),
        ),
        migrations.AddField(
            model_name='travelregistration',
            name='user_notes',
            field=models.TextField(blank=True, help_text='Any notes or other info we should know?', null=True),
        ),
    ]
