# Generated by Django 4.1.6 on 2023-02-09 23:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="TitoEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=256)),
                ("account_slug", models.CharField(max_length=64)),
                ("event_slug", models.CharField(max_length=128)),
                ("api_token", models.CharField(max_length=128)),
                ("webhook_endpoint", models.CharField(max_length=256)),
                ("tito_webhook_id", models.PositiveIntegerField(blank=True, null=True)),
                ("start_date", models.DateField(blank=True, null=True)),
                ("sales_start_date", models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="TitoWebhookEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                ("trigger", models.CharField(blank=True, max_length=256)),
                (
                    "tito_webhook_endpoint_id",
                    models.PositiveIntegerField(blank=True, null=True),
                ),
                (
                    "tito_signature",
                    models.CharField(blank=True, default="", max_length=512),
                ),
                ("payload", models.JSONField(blank=True, null=True)),
                ("payload_text", models.TextField(blank=True, default="")),
                ("processed", models.BooleanField(default=False)),
                ("processing_failed", models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name="TitoWebhookSetupLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                ("payload_text", models.TextField(blank=True, default="")),
                ("response_text", models.TextField(blank=True, default="")),
                (
                    "event",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="titowebhooks.titoevent",
                    ),
                ),
            ],
        ),
    ]
