# Generated by Django 5.1.15 on 2026-04-22 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('titowebhooks', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TitoHistoricalEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=128, unique=True)),
                ('year', models.PositiveIntegerField(db_index=True)),
                ('title', models.CharField(max_length=256)),
                ('account_slug', models.CharField(default='defna', max_length=64)),
                ('is_current', models.BooleanField(default=False)),
                ('releases', models.JSONField(blank=True, null=True)),
                ('last_synced', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-year'],
            },
        ),
    ]
