# Generated by Django 5.1.15 on 2026-04-22 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('titowebhooks', '0002_titohistoricalevent'),
    ]

    operations = [
        migrations.AddField(
            model_name='titohistoricalevent',
            name='goal',
            field=models.PositiveIntegerField(blank=True, help_text='Sales goal for this year', null=True),
        ),
    ]
