# Generated by Django 5.1.15 on 2026-04-22 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('titowebhooks', '0003_titohistoricalevent_goal'),
    ]

    operations = [
        migrations.AddField(
            model_name='titohistoricalevent',
            name='activities',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
