# Generated by Django 6.0.6 on 2026-08-03 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('titowebhooks', '0004_titohistoricalevent_activities'),
    ]

    operations = [
        migrations.AddField(
            model_name='titohistoricalevent',
            name='start_date',
            field=models.DateField(blank=True, help_text='First day of the conference; anchors days-out math', null=True),
        ),
        migrations.CreateModel(
            name='TitoTicket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_slug', models.SlugField(max_length=128)),
                ('year', models.PositiveIntegerField(db_index=True)),
                ('ticket_slug', models.CharField(max_length=128, unique=True)),
                ('reference', models.CharField(blank=True, max_length=64)),
                ('release_title', models.CharField(blank=True, max_length=256)),
                ('release_price', models.FloatField(default=0.0, help_text='List price of the release')),
                ('price', models.FloatField(default=0.0, help_text='What the attendee actually paid')),
                ('discount_code', models.CharField(blank=True, max_length=128)),
                ('state_name', models.CharField(blank=True, max_length=64)),
                ('voided', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('source', models.CharField(choices=[('api', 'Ti.to API'), ('webhook', 'Webhook')], default='api', max_length=16)),
                ('last_synced', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-year', 'created_at'],
                'indexes': [models.Index(fields=['year', 'created_at'], name='titowebhook_year_4b2b5b_idx')],
            },
        ),
    ]
