# Generated by Django 6.0.6 on 2026-08-03 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('titowebhooks', '0005_titohistoricalevent_start_date_titoticket'),
    ]

    operations = [
        migrations.AddField(
            model_name='titoticket',
            name='release_id',
            field=models.PositiveBigIntegerField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='titoticket',
            name='release_price',
            field=models.FloatField(default=0.0, help_text='List price as reported on the ticket itself; the /tickets API omits this, so prefer the release lookup'),
        ),
    ]
