# Generated by Django 6.0.6 on 2026-08-04 05:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('titowebhooks', '0006_titoticket_release_id_alter_titoticket_release_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='titoticket',
            name='email',
            field=models.EmailField(blank=True, db_index=True, help_text='Attendee address; blank until the ticket is claimed', max_length=254),
        ),
        migrations.AddField(
            model_name='titoticket',
            name='name',
            field=models.CharField(blank=True, max_length=256),
        ),
    ]
