# Generated by Django 6.0.6 on 2026-08-19 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('titowebhooks', '0007_titoticket_email_titoticket_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='TitoDiscountCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_slug', models.SlugField(max_length=128)),
                ('year', models.PositiveIntegerField(db_index=True)),
                ('tito_id', models.PositiveBigIntegerField()),
                ('code', models.CharField(max_length=128)),
                ('description', models.TextField(blank=True, help_text='Ti.to\'s own summary, e.g. "Sell for 100.0% less. 2/4 available."')),
                ('discount_type', models.CharField(blank=True, help_text='PercentOffDiscountCode or MoneyOffDiscountCode', max_length=64)),
                ('value', models.FloatField(default=0.0, help_text='Percent off, or dollars off, depending on discount_type')),
                ('quantity', models.PositiveIntegerField(blank=True, help_text='Redemptions issued; null means Ti.to placed no cap on this code', null=True)),
                ('quantity_used', models.PositiveIntegerField(default=0, help_text='Redemptions Ti.to has counted against the cap')),
                ('tickets_count', models.PositiveIntegerField(default=0)),
                ('registrations_count', models.PositiveIntegerField(default=0)),
                ('state', models.CharField(blank=True, help_text='current, past, or upcoming', max_length=32)),
                ('share_url', models.URLField(blank=True, max_length=512)),
                ('start_at', models.DateTimeField(blank=True, null=True)),
                ('end_at', models.DateTimeField(blank=True, null=True)),
                ('last_synced', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-year', 'code'],
                'constraints': [models.UniqueConstraint(fields=('event_slug', 'tito_id'), name='unique_discount_code_per_event')],
            },
        ),
    ]
