"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 4.1.6.

For more information on this file, see
https://docs.djangoproject.com/en/4.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.1/ref/settings/
"""

import datetime

import environs

env = environs.Env()


# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = environs.Path(__file__).parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = env.str("SECRET_KEY", default="django-insecure-37x6xs*$^dve-e2cl2htt+c3iew7bwmrrow)_rvz_f*+u*o8f6")

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = env.bool("DJANGO_DEBUG", default=False)

ALLOWED_HOSTS = env.list("ALLOWED_HOSTS", default=["*"])

CSRF_TRUSTED_ORIGINS = env.list(
    "CSRF_TRUSTED_ORIGINS",
    default=[
        "https://automation.defna.org",
        "http://localhost/",
    ],
)

SECURE_PROXY_SSL_HEADER = ("HTTP_X_FORWARDED_PROTO", "https")

# Application definition

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.sites",
    "django.contrib.staticfiles",
    "django_prodserver",
    "django_simple_nav",
    "django_tailwind_cli",
    "health_check",
    "health_check.db",
    "health_check.storage",
    "allauth",
    "allauth.account",
    "allauth.socialaccount",
    "allauth.socialaccount.providers.github",
    "django_q",
]

INSTALLED_APPS += [
    "emailoctopus",
    "thunderdome",
    "tickets",
    "titowebhooks",
    "travel_safety",
    "social_monitor",
    "volunteers",
]

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "whitenoise.middleware.WhiteNoiseMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
    "allauth.account.middleware.AccountMiddleware",
]

ROOT_URLCONF = "config.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [str(BASE_DIR.joinpath("templates"))],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
                "config.context_processors.app_version",
            ],
        },
    },
]

WSGI_APPLICATION = "config.wsgi.application"


# Database
# https://docs.djangoproject.com/en/4.1/ref/settings/#databases

DATABASES = {
    "default": env.dj_db_url(
        "DATABASE_URL",
        default="postgres://postgres@postgres/postgres",
    )
}


# Password validation
# https://docs.djangoproject.com/en/4.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.1/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = "America/Chicago"

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.1/howto/static-files/

# STORAGES = {
#     "default": {
#         "BACKEND": "django.core.files.storage.FileSystemStorage",
#     },
#     "staticfiles": {
#         "BACKEND": "whitenoise.storage.CompressedManifestStaticFilesStorage",
#     },
# }
STATIC_ROOT = f"{BASE_DIR}/staticfiles"
STATIC_URL = "static/"
STATICFILES_DIRS = (
    str(BASE_DIR.joinpath("frontend")),
    str(BASE_DIR.joinpath("static")),
)

# Default primary key field type
# https://docs.djangoproject.com/en/4.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

SITE_ID = 1

AUTHENTICATION_BACKENDS = [
    "django.contrib.auth.backends.ModelBackend",
    "allauth.account.auth_backends.AuthenticationBackend",
]

# Django Allauth settings

ACCOUNT_DEFAULT_HTTP_PROTOCOL = "https"
ACCOUNT_EMAIL_VERIFICATION = "none"
# Left unset, allauth prefixes every subject with "[{Site.name}] " — which in
# production is the bare hostname, so sign-in codes arrived as
# "[automation.defna.org] Sign-In Code". Our own emails carry the brand in the
# subject itself (see tickets/tasks.py SUBJECTS), so drop the prefix entirely
# and name DjangoCon US in the overridden *_subject.txt templates instead.
ACCOUNT_EMAIL_SUBJECT_PREFIX = ""
# Passwordless sign-in: allauth emails a short-lived code (and our email template
# adds a clickable link that prefills it). See #91/#99.
ACCOUNT_LOGIN_BY_CODE_ENABLED = True
# Allauth only mails a code to accounts that already exist; an unknown address
# gets a "no such account" email and a dead end. Attendees have no reason to
# have signed up first, so this form creates the account and carries on. The
# code still only goes to the address that was typed, which is what makes it
# safe to skip a password. See config/account_forms.py.
ACCOUNT_FORMS = {"request_login_code": "config.account_forms.AutoSignupRequestLoginCodeForm"}
ACCOUNT_LOGIN_METHODS = {"email"}
ACCOUNT_SIGNUP_FIELDS = ["email*", "password1*", "password2*"]
# NOTE: do not set ACCOUNT_USER_MODEL_USERNAME_FIELD = None. We use the stock
# auth.User, which has a UNIQUE username column. Setting this to None makes
# allauth's populate_username() a no-op, so users are saved with username="";
# the second such signup then dies on a UniqueViolation. See #89.
LOGIN_REDIRECT_URL = "/"
SOCIALACCOUNT_EMAIL_AUTHENTICATION = True
SOCIALACCOUNT_EMAIL_AUTHENTICATION_AUTO_CONNECT = True

# Logging
#
# Without this, DEBUG=False swallows 500 tracebacks entirely and the container
# logs show nothing. django.request is what logs unhandled view exceptions.

DJANGO_LOG_LEVEL = env.str("DJANGO_LOG_LEVEL", default="INFO")

LOGGING = {
    "version": 1,
    "disable_existing_loggers": False,
    "formatters": {
        "verbose": {
            "format": "{asctime} {levelname} {name} {message}",
            "style": "{",
        },
    },
    "handlers": {
        "console": {
            "class": "logging.StreamHandler",
            "formatter": "verbose",
        },
    },
    "root": {
        "handlers": ["console"],
        "level": DJANGO_LOG_LEVEL,
    },
    "loggers": {
        "django.request": {
            "handlers": ["console"],
            "level": "ERROR",
            "propagate": False,
        },
    },
}

# Email sending (#90). Configure entirely via EMAIL_URL, e.g.:
#   submission://USER:PASSWORD@smtp.example.com:587   (STARTTLS)
#   smtp://USER:PASSWORD@smtp.example.com:465?ssl=True (implicit TLS)
# The default is the console backend, so environments without EMAIL_URL print
# emails to stdout instead of dying with ConnectionRefusedError on localhost:25.
# An unrecognized scheme fails at startup with KeyError("EMAIL_BACKEND") — loud
# beats silently sending nothing.

email = env.dj_email_url("EMAIL_URL", default="console://")
EMAIL_BACKEND = email["EMAIL_BACKEND"]
EMAIL_HOST = email["EMAIL_HOST"]
EMAIL_PORT = email["EMAIL_PORT"]
EMAIL_HOST_USER = email["EMAIL_HOST_USER"]
EMAIL_HOST_PASSWORD = email["EMAIL_HOST_PASSWORD"]
EMAIL_USE_TLS = email["EMAIL_USE_TLS"]
EMAIL_USE_SSL = email["EMAIL_USE_SSL"]
EMAIL_TIMEOUT = env.int("EMAIL_TIMEOUT", default=10)

# Forward Email rejects any message whose From header does not match the mailbox
# we authenticate as, with "550 5.1.1 From header must be equal to
# hello@mail.defna.org". Keep these in sync with the EMAIL_URL credentials.
DEFAULT_FROM_EMAIL = env.str("DEFAULT_FROM_EMAIL", default="DjangoCon US <hello@mail.defna.org>")
SERVER_EMAIL = env.str("SERVER_EMAIL", default="hello@mail.defna.org")

# Email Octopus API settings

EMAILOCTOPUS_API_KEY = env("EMAILOCTOPUS_API_KEY", default="")

# django-prodserver settings

PRODUCTION_PROCESSES = {
    "web": {
        "BACKEND": "django_prodserver.backends.gunicorn.GunicornServer",
        "ARGS": {"bind": "0.0.0.0:8000", "workers": "2"},
    },
    "worker": {
        "BACKEND": "django_prodserver.backends.django_q2.DjangoQ2Worker",
        "ARGS": {},
    },
}

# django-q settings

Q_CLUSTER = {
    "bulk": 10,
    "max_attempts": 1,
    "name": "DjangORM",
    "orm": "default",
    "queue_limit": 50,
    "retry": 120,
    "timeout": 90,
    "workers": 2,
}

Q_SCHEDULES = {
    "emailoctopus-sync-campaigns": {
        "func": "emailoctopus.utils.sync_campaigns",
        "schedule_type": "HOURLY",
    },
    "travel-safety-retention-policy": {
        "func": "travel_safety.tasks.enforce_retention",
        "schedule_type": "DAILY",
    },
    "volunteer-shift-reminders": {
        "func": "volunteers.tasks.send_shift_reminders",
        "schedule_type": "HOURLY",
    },
}

# Volunteer signup settings

VOLUNTEER_MAX_HOURS = env.int("VOLUNTEER_MAX_HOURS", default=8)

# Coordinators to alert when a near-term shift loses its last volunteer (#84).
# Empty (the default) disables the alert entirely.
VOLUNTEER_COORDINATOR_EMAILS = env.list("VOLUNTEER_COORDINATOR_EMAILS", default=[])

# Only alert for shifts starting within this window...
VOLUNTEER_UNCOVERED_ALERT_WINDOW_HOURS = env.int("VOLUNTEER_UNCOVERED_ALERT_WINDOW_HOURS", default=48)

# ...and skip the alert when the volunteer signed up and cancelled within this
# buffer — a quick change of mind isn't worth an email.
VOLUNTEER_UNCOVERED_ALERT_BUFFER_MINUTES = env.int("VOLUNTEER_UNCOVERED_ALERT_BUFFER_MINUTES", default=60)

# Shared address for the volunteer chairs, shown on a volunteer's own page so
# nobody's personal inbox is published. Set per environment; blank (the default)
# hides the link.
VOLUNTEER_CONTACT_EMAIL = env.str("VOLUNTEER_CONTACT_EMAIL", default="")

# General volunteer handbook, shown alongside role-specific docs.
VOLUNTEER_HANDBOOK_URL = env.str(
    "VOLUNTEER_HANDBOOK_URL",
    default="https://docs.google.com/document/d/1jpRr5jUxiQCgeXvnX-RPee1AsB1parzHRzCg3YcLCXA/edit?usp=sharing",
)

# Slack settings

SLACK_OAUTH_TOKEN = env("SLACK_OAUTH_TOKEN", default="")
SLACK_CHANNEL_ID = env("SLACK_CHANNEL_ID", default="")

# Conference settings

CONFERENCE_END_DATE = env.date("CONFERENCE_END_DATE", default=datetime.date(2026, 8, 28))

# Tito settings

TITO_SECURITY_TOKEN = env("TITO_SECURITY_TOKEN", default="")
TITO_API_TOKEN = env("TITO_API_TOKEN", default="")
TITO_ACCOUNT_SLUG = env("TITO_ACCOUNT_SLUG", default="defna")
TITO_EVENT_SLUG = env("TITO_EVENT_SLUG", default="")

# Tailwind CSS settings

TAILWIND_CLI_AUTOMATIC_DOWNLOAD = env.bool("TAILWIND_CLI_AUTOMATIC_DOWNLOAD", default=True)
TAILWIND_CLI_CONFIG_FILE = env.str("TAILWIND_CLI_CONFIG_FILE", default="tailwind.config.js")
TAILWIND_CLI_DIST_CSS = env.str("TAILWIND_CLI_DIST_CSS", default="css/tailwind.css")
TAILWIND_CLI_PATH = env.str("TAILWIND_CLI_PATH", default="~/.local/bin/")
TAILWIND_CLI_SRC_CSS = env.str("TAILWIND_CLI_SRC_CSS", default="frontend/index.css")
TAILWIND_CLI_VERSION = env.str("TAILWIND_CLI_VERSION", default="4.1.18")

# Social monitor

MASTODON_ACCESS_TOKEN = env("MASTODON_ACCESS_TOKEN", default="")
MASTODON_API_BASE_URL = env("MASTODON_API_BASE_URL", default="https://mastodon.social")
