# Generated by Django 5.1.15 on 2026-03-24 18:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('pretalx_slug', models.SlugField(help_text='Event slug used in pretalx API URLs', max_length=200, unique=True)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('slots_25_in_person', models.PositiveIntegerField(default=0, verbose_name='25-min in-person slots')),
                ('slots_45_in_person', models.PositiveIntegerField(default=0, verbose_name='45-min in-person slots')),
                ('slots_25_online', models.PositiveIntegerField(default=0, verbose_name='25-min online slots')),
                ('slots_45_online', models.PositiveIntegerField(default=0, verbose_name='45-min online slots')),
                ('pretalx_token', models.CharField(blank=True, help_text='Pretalx API token for this event', max_length=200)),
            ],
            options={
                'ordering': ['-start_date'],
            },
        ),
        migrations.CreateModel(
            name='Speaker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('pretalx_code', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('pretalx_id', models.CharField(blank=True, max_length=100, null=True, unique=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Submission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pretalx_id', models.CharField(db_index=True, max_length=100)),
                ('title', models.CharField(max_length=500)),
                ('track', models.CharField(blank=True, max_length=200)),
                ('duration', models.PositiveIntegerField(blank=True, choices=[(25, '25 minutes'), (45, '45 minutes')], null=True)),
                ('state', models.CharField(choices=[('submitted', 'Submitted'), ('accepted-in-person', 'Accepted (In-Person)'), ('accepted-online', 'Accepted (Online)'), ('waitlist-in-person', 'Waitlist (In-Person)'), ('waitlist-online', 'Waitlist (Online)'), ('rejected', 'Rejected'), ('confirmed', 'Confirmed'), ('canceled', 'Canceled'), ('withdrawn', 'Withdrawn')], default='submitted', max_length=30)),
                ('abstract', models.TextField(blank=True)),
                ('description', models.TextField(blank=True)),
                ('notes', models.TextField(blank=True, help_text="Speaker's notes to reviewers")),
                ('internal_notes', models.TextField(blank=True, help_text='Internal organizer notes')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='thunderdome.event')),
                ('speakers', models.ManyToManyField(blank=True, related_name='submissions', to='thunderdome.speaker')),
                ('tags', models.ManyToManyField(blank=True, related_name='submissions', to='thunderdome.tag')),
            ],
            options={
                'ordering': ['title'],
                'unique_together': {('event', 'pretalx_id')},
            },
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.PositiveIntegerField(blank=True, choices=[(0, 'No'), (1, 'Maybe'), (2, 'Yes')], null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='thunderdome_reviews', to=settings.AUTH_USER_MODEL)),
                ('submission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='thunderdome.submission')),
            ],
            options={
                'ordering': ['-created_at'],
                'unique_together': {('submission', 'user')},
            },
        ),
    ]
