# Generated by Django 5.1.15 on 2026-03-24 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('thunderdome', '0002_alter_review_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='pretalx_state',
            field=models.CharField(choices=[('submitted', 'Submitted'), ('accepted', 'Accepted'), ('confirmed', 'Confirmed'), ('rejected', 'Rejected'), ('canceled', 'Canceled'), ('withdrawn', 'Withdrawn')], default='submitted', help_text='State synced from pretalx', max_length=30),
        ),
        migrations.AlterField(
            model_name='submission',
            name='state',
            field=models.CharField(choices=[('unreviewed', 'Unreviewed'), ('accepted-in-person', 'Accepted (In-Person)'), ('accepted-online', 'Accepted (Online)'), ('waitlist-in-person', 'Waitlist (In-Person)'), ('waitlist-online', 'Waitlist (Online)'), ('rejected', 'Rejected')], default='unreviewed', help_text='Thunderdome decision', max_length=30),
        ),
    ]
