# Generated by Django 5.1.15 on 2026-04-16 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('thunderdome', '0003_submission_pretalx_state_alter_submission_state'),
    ]

    operations = [
        migrations.AddField(
            model_name='speaker',
            name='applied_for_grant',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='speaker',
            name='email',
            field=models.EmailField(blank=True, max_length=254),
        ),
    ]
