# Generated by Django 4.2.11 on 2024-09-14 00:23

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="TicketLink",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("link", models.URLField()),
                ("date_link_accessed", models.DateTimeField(blank=True, null=True)),
                ("date_link_created", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
