# Generated by Django 4.2.11 on 2025-08-28 23:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tickets", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="ticketlink",
            name="attendee_email",
            field=models.EmailField(blank=True, db_index=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name="ticketlink",
            name="date_link_assigned",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddConstraint(
            model_name="ticketlink",
            constraint=models.UniqueConstraint(
                condition=models.Q(("attendee_email__isnull", False)),
                fields=("attendee_email",),
                name="unique_attendee_email",
            ),
        ),
    ]
