# Generated by Django 4.2.11 on 2025-08-29 01:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0002_ticketlink_attendee_email_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticketlink',
            name='date_link_accessed',
        ),
    ]
