# Generated by Django 6.0.6 on 2026-08-04 05:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0003_remove_date_link_accessed'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OnlineAttendee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(db_index=True, max_length=254)),
                ('name', models.CharField(blank=True, max_length=256)),
                ('year', models.PositiveIntegerField(db_index=True)),
                ('release_title', models.CharField(blank=True, max_length=256)),
                ('purchased_at', models.DateTimeField(blank=True, null=True)),
                ('source', models.CharField(choices=[('tito_api', 'Ti.to API'), ('webhook', 'Webhook'), ('manual', 'Added by staff')], default='tito_api', max_length=16)),
                ('last_synced', models.DateTimeField(blank=True, null=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-year', 'name', 'email'],
            },
        ),
        migrations.CreateModel(
            name='TicketEmailLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('to_email', models.EmailField(db_index=True, max_length=254)),
                ('kind', models.CharField(choices=[('initial', 'Initial send'), ('resend', 'Resend of same link'), ('reissue', 'New link issued')], default='initial', max_length=16)),
                ('status', models.CharField(choices=[('queued', 'Queued'), ('sent', 'Sent'), ('failed', 'Failed')], default='queued', max_length=16)),
                ('subject', models.CharField(blank=True, max_length=512)),
                ('error', models.TextField(blank=True)),
                ('date_queued', models.DateTimeField(auto_now_add=True)),
                ('date_sent', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-date_queued'],
            },
        ),
        migrations.RemoveConstraint(
            model_name='ticketlink',
            name='unique_attendee_email',
        ),
        migrations.AddField(
            model_name='ticketlink',
            name='superseded_at',
            field=models.DateTimeField(blank=True, help_text='Set when a replacement link is issued; the old link stays for the audit trail.', null=True),
        ),
        migrations.AddConstraint(
            model_name='onlineattendee',
            constraint=models.UniqueConstraint(fields=('year', 'email'), name='unique_attendee_per_year'),
        ),
        migrations.AddField(
            model_name='ticketlink',
            name='attendee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ticket_links', to='tickets.onlineattendee'),
        ),
        migrations.AddConstraint(
            model_name='ticketlink',
            constraint=models.UniqueConstraint(condition=models.Q(('attendee_email__isnull', False), ('superseded_at__isnull', True)), fields=('attendee_email',), name='unique_active_attendee_email'),
        ),
        migrations.AddField(
            model_name='ticketemaillog',
            name='attendee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='email_logs', to='tickets.onlineattendee'),
        ),
        migrations.AddField(
            model_name='ticketemaillog',
            name='sent_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ticket_emails_sent', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='ticketemaillog',
            name='ticket_link',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='email_logs', to='tickets.ticketlink'),
        ),
        migrations.AddIndex(
            model_name='ticketemaillog',
            index=models.Index(fields=['to_email', '-date_queued'], name='tickets_tic_to_emai_1e98fb_idx'),
        ),
    ]
