# Generated by Django 6.0.6 on 2026-08-18 02:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0004_onlineattendee_ticketemaillog_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TicketRelease',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=256, unique=True)),
                ('last_seen_year', models.PositiveIntegerField(blank=True, db_index=True, help_text='Most recent conference year this ticket type was sold in.', null=True)),
                ('release_id', models.PositiveBigIntegerField(blank=True, db_index=True, help_text="Ti.to's own id for the release. Stable across title edits.", null=True)),
                ('grants_venueless_access', models.BooleanField(default=False, help_text='Buyers of this ticket type belong on the Venueless roster.')),
                ('last_synced', models.DateTimeField(blank=True, null=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['title'],
            },
        ),
    ]
