# Generated by Django 5.1.15 on 2026-03-25 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Campaign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('list_id', models.CharField(max_length=64)),
                ('name', models.CharField(max_length=100)),
                ('active', models.BooleanField(default=True)),
                ('default', models.BooleanField(default=False)),
            ],
        ),
    ]
